var number1 = 10;
var number2 = 2;
var soma = number1 + number2;
var subtracao = number1 - number2;
var multiplicacao = number1 * number2;
var divisao = number1 / number2;
console.log(soma);
console.log(subtracao);
console.log(multiplicacao);
console.log(divisao);
